### PR TITLE
Add function to create overlays

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by MarvinTeichmann** [comment]
I do not really like the interface of the function `overlay_images`. `original_image` image is read from the disk and the overlay-image is saved automatically. There are many cases where this is not what is desired. 

Inside a training algorithm the image is usually already inside the memory as numpy array. Additional one does not necessarily want to write the result to disk. An application might want to pass the result to Tensorboard. 

I think the utility function which take and return numpy arrays are much more useful. The user than can decide how to process the overlay.

I have provided a modified version in 83a1fdd1e2e6cdd79d41f1c7baebd5dfa43abf8b.

**Comment by MartinThoma** [comment]
@MarvinTeichmann Thank you for your detailed suggestions. I've updated my pull request to include those changes. (I also didn't like the interface I chose)

**Comment by MarvinTeichmann** [comment]
What do you think about my other overlay function (i.e. `make_soft_overlay`)? That one is very nice when analyzing the behavior of one class (in multi class scenarios) and in two-class cases.

**Comment by MartinThoma** [comment]
I wrote a test and it didn't work: http://imgur.com/a/DitOZ

```python
def test_soft_overlay_segmentation():
    """Test soft_overlay_segmentation."""
    from tensorvision.utils import soft_overlay_segmentation
    import scipy.ndimage
    import numpy as np
    seg_image = 'tensorvision/tests/Crocodylus-johnsoni-3-seg-prob.png'
    original_image = 'tensorvision/tests/Crocodylus-johnsoni-3.jpg'
    target_path = 'tensorvision/tests/croco-overlay-new-soft.png'
    correct_path = 'tensorvision/tests/croco-overlay.png'
    input_image = scipy.misc.imread(original_image)
    segmentation = scipy.misc.imread(seg_image)
    print(segmentation)
    res = soft_overlay_segmentation(input_image, segmentation)
    scipy.misc.imsave(target_path, res)
    img1 = scipy.ndimage.imread(correct_path)
    img2 = scipy.ndimage.imread(target_path)
    assert np.array_equal(img1, img2)
```

**Comment by MartinThoma** [comment]
Never mind, I've just seen that the issue is due to the color maps colors. I've made your code more flexible and added some documentation. It's not part of the pull request.

**Comment by MarvinTeichmann** [comment]
Looks nice! Feel free to merge.

**Pull request merged**
